blank_issues_enabled: yes
contact_links:
  - name: GitHub Discussions
    url: https://github.com/meehl/rusty-path-of-building/discussions
    about: Please ask questions unrelated to actual bugs/issues here.
